#!/bin/bash

function autozip(){
#改行のみ
IFS_BACKUP=$IFS
IFS=$'\n'
CROME_DFILESP=$CROME_DFILES/*
echo $CROME_DFILESP 
cd $CROME_DFILESP

for filepath in ${CROME_DFILESP}
do
  array+=(${filepath})
  	echo $filename
done



for i in `seq 1 ${#array[@]}`
do
 

if [ '0' = ${#array[@]} ]; then
	echo "no file"
	exit 0
fi
 

#zip
if [ 'zip' = ${array[$i-1]##*.} ]; then

		
 		# tmp_filename=`basename ${array[$i-1]}`
 		# tmp_filename=${tmp_filename%.*} #ファイル名のみ取得

		expect -c "
		set timeout 300
		spawn unzip ${array[$i-1]}
		expect {
		    \"replace\" { send \"A\n\" }
		}
		interact
		"
		sleep 3
		rm ${array[$i-1]}
		echo "create:"${array[$i-1]%.*}"\n"
		echo "and delete\n"
		
fi	

echo ${array[$i-1]##*.}
#tar.gz
if [ 'gz' = ${array[$i-1]##*.} ]; then
 
		expect -c "
		set timeout 300
		spawn tar zxvf ${array[$i-1]}
		expect {
		    \"replace\" { send \"A\n\" }
		}
		interact
		"
		sleep 3
		rm ${array[$i-1]}
		echo "create:"${array[$i-1]%.*}"\n"
		echo "and delete\n"
		
fi	


done

#元に戻す
IFS=$IFS_BACKUP
}


fswatch -0 /Users/jima/Desktop | while read -d "" event 
  do 
    autozip 
  done


