#!/bin/bash


n=0

#プロセスIDを格納
TMP_PID=(`sh ~/myshell/tmp/kip_pid.sh`)
TMP_NAME=(`sh ~/myshell/tmp/kip_name.sh`)

#プロセスの名前から一致する奴を検索
for x in `sh ~/myshell/tmp/kip_name.sh`;
do
    if [[ $x = $1 ]]; 
    then
    		#echo "一致"
        Array+=($n)
    fi
    n=`expr $n + 1`
done

for x in ${Array[@]} ;
do
	#	echo $x
	#	echo ${TMP_PID[x]}
		kill -9 ${TMP_PID[x]}
    n=`expr $n + 1`
    echo "Name ${TMP_NAME[x]},PID ${TMP_PID[x]} killed"
done
echo "kill completed!!"

